////Array Methods
let fruits=["apple","mango","banana","grapes","pineapple"]
console.log(fruits)
console.log(typeof(fruits))
let no=[[1],2,3,4,5]
console.log(fruits.concat(no))
console.log(no.flat(1))
console.log(fruits.includes("apple"))
console.log(fruits.indexOf("apple"))
console.log(fruits.lastIndexOf("grapes"))
console.log(fruits.join("/"))
console.log(fruits.pop())
console.log(fruits.push("cake"))
console.log(fruits)
console.log(fruits.reverse())
console.log(fruits.shift())
console.log(fruits.unshift("aaa"))
console.log(fruits)
console.log(fruits.slice(1,3))
console.log(fruits.slice(2))
console.log(fruits.slice(-2))
console.log(fruits.splice(0,2))
console.log(fruits)
console.log(fruits.splice(3,0,"chethan"))
console.log(fruits)
console.log(fruits)